### ISSUE TITLE
Create nginx_container

### ISSUE THREAD

**Issue by gregorwebmaster** [gregorwebmaster/ngino_webserver#4]
* create a container based on nginx:1.13.3-alpine
* expose port 80, 443, 8080
* create server configuration
* create exemplar pages: ngido-dev & ngido-prod
* create vhosts configuration
* add nginx to docker compose file

```
  nginx:
    build: ./images/nginx
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./data/www:/var/www
      - ./config/nginx/vhosts:/etc/nginx/vhosts
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
```
