### ISSUE TITLE
Create mysql container

### ISSUE THREAD

**Issue by gregorwebmaster** [gregorwebmaster/ngino_webserver#9]
* create a container based on official image mysql:5.7.19
* add container to docker compose file
* bind to php container
* add phpmyadmin based on official image phpmyadmin/phpmyadmin
* bind phppmyadmin to port 8855

```
  mysql:
    image: mysql:5.7.19
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=yourRootPassword
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8855:80
    volumes:
      - /sessions
```
